<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <NoWarn>$(NoWarn);NU1507</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <GlobalPackageReference Include="CSharpier.MSBuild" Version="1.2.1" />
  </ItemGroup>
  <ItemGroup>
    <PackageVersion Include="Antlr4.Runtime.Standard" Version="4.13.1" />
    <PackageVersion Include="AssetRipper.CIL" Version="1.2.1" />
    <PackageVersion Include="AssetRipper.ICSharpCode.Decompiler" Version="10.0.0.8172-preview2" />
    <PackageVersion Include="AssetRipper.Text.SourceGeneration" Version="1.2.2" />
    <PackageVersion Include="Cake.Common" Version="6.0.0" />
    <PackageVersion Include="Cake.Core" Version="6.0.0" />
    <PackageVersion Include="Cake.FileHelpers" Version="7.0.0" />
    <PackageVersion Include="Cake.CMake" Version="1.4.0" />
    <PackageVersion Include="ConsoleAppFramework" Version="5.7.11" />
    <PackageVersion Include="LLVMSharp" Version="20.1.2" />
    <PackageVersion Include="LLVMSharp.Interop" Version="20.1.2" />
    <PackageVersion Include="Microsoft.CodeAnalysis.Analyzers" Version="4.14.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="4.14.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageVersion Include="NuGet.Configuration" Version="6.14.0" />
    <PackageVersion Include="NUnit" Version="4.4.0" />
    <PackageVersion Include="NUnit.Analyzers" Version="4.10.0" />
    <PackageVersion Include="NUnit3TestAdapter" Version="5.1.0" />
    <PackageVersion Include="Ookii.CommandLine" Version="5.0.0" />
    <PackageVersion Include="PolySharp" Version="1.15.0" />
    <PackageVersion Include="Shouldly" Version="4.3.0" />
    <PackageVersion Include="SourceGenerator.Foundations" Version="2.0.13" />
    <PackageVersion Include="System.IO.Hashing" Version="9.0.9" />
    <PackageVersion Include="System.Numerics.Tensors" Version="10.0.0-preview.5.25277.114" />
    <PackageVersion Include="System.CommandLine" Version="2.0.0" />
  </ItemGroup>
</Project>
