<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Ookii.CommandLine" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference
      Include="..\AssetRipper.Translation.LlvmIR\AssetRipper.Translation.LlvmIR.csproj"
      IncludeAssets="all"
    />
  </ItemGroup>
</Project>
