<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishAot>true</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
    <RootNamespace>AssetRipper.Translation.LlvmIR.Build.Scripts.Tooling</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Cake.Common" />
    <PackageReference Include="Cake.Core" />
    <PackageReference Include="NuGet.Configuration" />
    <PackageReference Include="Shouldly" />
  </ItemGroup>
</Project>
