<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <LangVersion>preview</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Antlr4.Runtime.Standard" />
    <PackageReference Include="AssetRipper.CIL" />
    <PackageReference Include="AssetRipper.ICSharpCode.Decompiler" />
    <PackageReference Include="LLVMSharp" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    <PackageReference Include="System.IO.Hashing" />
    <PackageReference Include="System.Numerics.Tensors" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference
      Include="..\AssetRipper.Translation.LlvmIR.Shims.Native\AssetRipper.Translation.LlvmIR.Shims.Native.csproj"
      IncludeAssets="all"
    />
    <ProjectReference
      Include="..\AssetRipper.Translation.LlvmIR.SourceGenerator\AssetRipper.Translation.LlvmIR.SourceGenerator.csproj"
      OutputItemType="Analyzer"
      ReferenceOutputAssembly="false"
    />
  </ItemGroup>
</Project>
